name: Release

on:
  release:
    types: [prereleased,released] 
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      actions: read
    
    env:
      NDK_VERSION: "r26d"
      API_LEVEL: "21"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download Android NDK
        run: |
          mkdir -p $HOME/android-ndk
          wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip
          unzip -q android-ndk-$NDK_VERSION-linux.zip -d $HOME/android-ndk
          mv $HOME/android-ndk/android-ndk-$NDK_VERSION $HOME/android-ndk/ndk
        shell: bash

      - name: Set up NDK environment
        run: |
          echo "NDK_ROOT=$HOME/android-ndk/ndk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-ndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          mkdir build
          bash build.sh
      
      - name: Upload binaries
        run: |
          cd build
          for file in *; do
            echo "Uploading $file"
            curl -s --fail --retry 3 --retry-delay 0 -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/octet-stream" --data-binary "@$file" "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=$file"
          done